// src/app/shared/rux.imports.ts
import {
    RuxButton,
    RuxContainer,
    RuxIcon,
    RuxInput,
    RuxSwitch,
    RuxTable,
    RuxTableHeader,
    RuxTabs,
    RuxTextarea,
    RuxNotification,
    RuxStatus,
    RuxSlider,
    RuxCheckbox,
    RuxTableHeaderRow,
    RuxTableHeaderCell,
    RuxTableBody,
    RuxTableRow,
    RuxTableCell,
} from '@astrouxds/angular';

export const RUX_IMPORTS = [
    RuxButton,
    RuxContainer,
    RuxIcon,
    RuxInput,
    RuxSwitch,
    RuxTable,
    RuxTableHeader,
    RuxTableHeaderRow,
    RuxTableHeaderCell,
    RuxTableBody,
    RuxTableRow,
    RuxTableCell,
    RuxTabs,
    RuxTextarea,
    RuxNotification,
    RuxStatus,
    RuxSlider,
    RuxCheckbox,
];
